# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do
    build_name = ENV['BUILD_VERSION']
    json_key = ENV['GOOGLE_JSON_KEY']
    aab_file = ENV['AAB_FILE']
    previous_build_number = google_play_track_version_codes(
      track: "internal",
      json_key: json_key
    )[0]
    new_build_number = previous_build_number + 1
    upload_to_play_store(track: 'internal', version_name:build_name, version_code:new_build_number, aab: aab_file, json_key: json_key)
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end
